# Form implementation generated from reading ui file 'Lab_1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import UiParamList
from NaturalNumberValidator import setValidator
from PyQt6.QtGui import QPixmap
from MyListWidgetClass import MyListWidgetClass
from myQTFunctions import getIntFromLineEdit
from UiValues import UiValues
import UiParamList


class Ui_MainWindow(object):
    photoWidth = 400
    maxLengthOfList = 30
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Lab_1 Тютюнов, Лукьяненко, Букин")
        MainWindow.resize(412, 483)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)#Главный виджет
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")

        self.Function_ComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Function_ComboBox.setObjectName("Function_ComboBox")
        for i in range(9):
            self.Function_ComboBox.addItem("")
        self.verticalLayoutMain.addWidget(self.Function_ComboBox)

        self.NumberInput_FormLayout = QtWidgets.QFormLayout()
        self.NumberInput_FormLayout.setContentsMargins(10, 10, 10, 10)
        self.NumberInput_FormLayout.setSpacing(7)
        self.NumberInput_FormLayout.setObjectName("NumberInput_FormLayout")

        self.Input_Label1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Input_Label1.setObjectName("Input_Label1")
        self.Input_Label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Input_Label2.setObjectName("Input_Label2")
        self.Input_Label3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Input_Label3.setObjectName("Input_Label3")
        self.Input_LineEdit1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_LineEdit1.setObjectName("Input_LineEdit1")
        self.Input_LineEdit2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_LineEdit2.setObjectName("Input_LineEdit2")
        self.Input_LineEdit3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_LineEdit3.setObjectName("Input_LineEdit3")

        self.NumberInput_FormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Input_Label1)
        self.NumberInput_FormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Input_LineEdit1)
        self.NumberInput_FormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Input_Label2)
        self.NumberInput_FormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Input_LineEdit2)
        self.NumberInput_FormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Input_Label3)
        self.NumberInput_FormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Input_LineEdit3)

        self.verticalLayoutMain.addLayout(self.NumberInput_FormLayout)

        self.Scroll_BoxLayout = QtWidgets.QVBoxLayout()
        self.Scroll_BoxLayout.setContentsMargins(10, 10, 10, 10)
        self.Scroll_BoxLayout.setObjectName("Scroll_BoxLayout")

        self.Scroll_Label1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Scroll_Label1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Scroll_Label1.setObjectName("Scroll_Label1")
        self.Scroll_BoxLayout.addWidget(self.Scroll_Label1)

        self.myListWidgetClass1 = MyListWidgetClass(self.centralwidget)
        self.Scroll_BoxLayout.addWidget(self.myListWidgetClass1.scrollArea)

        self.Scroll_Label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Scroll_Label2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Scroll_Label2.setObjectName("Scroll_Label2")
        self.Scroll_BoxLayout.addWidget(self.Scroll_Label2)

        self.myListWidgetClass2 = MyListWidgetClass(self.centralwidget)
        self.Scroll_BoxLayout.addWidget(self.myListWidgetClass2.scrollArea)

        self.verticalLayoutMain.addLayout(self.Scroll_BoxLayout)

        self.Result_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Result_Label.setObjectName("Result_Label")
        self.verticalLayoutMain.addWidget(self.Result_Label)

        self.Formula_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Formula_Label.setObjectName("Formula_Label")
        self.verticalLayoutMain.addWidget(self.Formula_Label)

        self.Photo_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Photo_Label.setObjectName("Photo_Label")
        self.verticalLayoutMain.addWidget(self.Photo_Label)

        self.Calculate_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Calculate_Button.setObjectName("Calculate_Button")
        self.verticalLayoutMain.addWidget(self.Calculate_Button)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.setTabOder(MainWindow)

        self.paramList = UiParamList.paramList()

        self.setValidators()
        self.setListeners()
        self.changeMod(self.Function_ComboBox.currentIndex(), self.Function_ComboBox.currentText())
    def setListeners(self):
        self.Function_ComboBox.currentIndexChanged.connect(lambda: self.changeMod(self.Function_ComboBox.currentIndex(), self.Function_ComboBox.currentText()))
        self.Input_LineEdit1.textChanged.connect(
            lambda: self.lineEditListener(
                self.Function_ComboBox.currentIndex(),
                1,
                getIntFromLineEdit(self.Input_LineEdit1)
            )
        )
        self.Input_LineEdit2.textChanged.connect(
            lambda: self.lineEditListener(
                self.Function_ComboBox.currentIndex(),
                2,
                getIntFromLineEdit(self.Input_LineEdit2)
            )
        )
        self.Input_LineEdit2.textChanged.connect(
            lambda: self.lineEditListener(
                self.Function_ComboBox.currentIndex(),
                3,
                getIntFromLineEdit(self.Input_LineEdit3)
            )
        )
        self.Calculate_Button.clicked.connect(lambda: self.calculateResult(self.Function_ComboBox.currentIndex()))
    def setValidators(self):
        setValidator(self.Input_LineEdit1)
        setValidator(self.Input_LineEdit2)
        setValidator(self.Input_LineEdit3)
    def changeMod(self, index, text):
        #проверка на диапазон
        if index < 0 or index >= len(self.paramList):
            print("Выход за пределы массивы параметров!")
            return
        param = self.paramList[index] #параметры для текущей формулы

        self.Input_Label1.setVisible(param.lineEditVisibility1)
        self.Input_LineEdit1.setVisible(param.lineEditVisibility1)
        if param.lineEditVisibility1:
            self.Input_Label1.setText(param.labelText1)

        self.Input_Label2.setVisible(param.lineEditVisibility2)
        self.Input_LineEdit2.setVisible(param.lineEditVisibility2)
        if param.lineEditVisibility2:
            self.Input_Label2.setText(param.labelText2)

        self.Input_Label3.setVisible(param.lineEditVisibility3)
        self.Input_LineEdit3.setVisible(param.lineEditVisibility3)
        if param.lineEditVisibility3:
            self.Input_Label3.setText(param.labelText3)

        self.myListWidgetClass1.scrollArea.setVisible(param.listVisibility1)
        self.Scroll_Label1.setVisible(param.listVisibility1)
        if param.listVisibility1:
            self.Scroll_Label1.setText(param.labelListText1)
            self.myListWidgetClass1.nameElement = param.nameElementList1
            self.myListWidgetClass1.setNumOfListElements(0)

        self.myListWidgetClass2.scrollArea.setVisible(param.listVisibility2)
        self.Scroll_Label2.setVisible(param.listVisibility2)
        if param.listVisibility2:
            self.Scroll_Label2.setText(param.labelListText2)
            self.myListWidgetClass2.nameElement = param.nameElementList2
            self.myListWidgetClass2.setNumOfListElements(0)

        pixmap = QPixmap(param.pictureName + ".png").scaledToWidth(self.photoWidth)
        self.Photo_Label.setPixmap(pixmap)
    def calculateResult(self, numOfOperation):
        # проверка на диапазон
        if numOfOperation < 0 or numOfOperation >= len(self.paramList):
            print("Выход за пределы массивы параметров!")
            return
        param = self.paramList[numOfOperation]  # параметры для текущей формулы
        try:
            values = UiValues()
            if param.needNum1:
                values.num1 = getIntFromLineEdit(self.Input_LineEdit1)
            if param.needNum2:
                values.num2 = getIntFromLineEdit(self.Input_LineEdit2)
            if param.needNum3:
                values.num3 = getIntFromLineEdit(self.Input_LineEdit3)
            if param.needList1:
                values.list1 = self.myListWidgetClass1.getList()
            if param.needList2:
                values.list2 = self.myListWidgetClass2.getList()
            res = param.function(values)
            if res < 0:
                text = "Некорректный ввод!"
            else:
                text = "Результат: "+str(res)
        except:
            text = "Невозможно посчитать значение"
        self.Result_Label.setText(text)
    def lineEditListener(self, currentFunctionIndex, numLineEdit, number):
        # проверка на диапазон
        if currentFunctionIndex < 0 or currentFunctionIndex >= len(self.paramList):
            print("Выход за пределы массива параметров!")
            return
        param = self.paramList[currentFunctionIndex]  # параметры для текущей формулы

        if (param.listVisibility1 and param.numOfLineEditListenerList1 == numLineEdit):
            num = min(param.maxLengthOfList1, number)
            self.myListWidgetClass1.setNumOfListElements(num)

        if (param.listVisibility2 and param.numOfLineEditListenerList2 == numLineEdit):
            num = min(param.maxLengthOfList2, number)
            self.myListWidgetClass2.setNumOfListElements(num)
    def setTabOder(self, MainWindow):
        scrollArea1 = self.myListWidgetClass1.scrollArea
        scrollArea2 = self.myListWidgetClass2.scrollArea
        MainWindow.setTabOrder(self.Function_ComboBox, self.Input_LineEdit1)
        MainWindow.setTabOrder(self.Input_LineEdit1, self.Input_LineEdit2)
        MainWindow.setTabOrder(self.Input_LineEdit2, self.Input_LineEdit3)
        MainWindow.setTabOrder(self.Input_LineEdit3, scrollArea1)
        MainWindow.setTabOrder(scrollArea1, scrollArea2)
        MainWindow.setTabOrder(scrollArea2, self.Calculate_Button)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab_1 Тютюнов, Лукьяненко, Букин"))

        self.Function_ComboBox.setItemText(0, _translate("MainWindow", "Перестановка без повторений"))
        self.Function_ComboBox.setItemText(1, _translate("MainWindow", "Сочетание без повторений"))
        self.Function_ComboBox.setItemText(2, _translate("MainWindow", "Размещение без повторений"))
        self.Function_ComboBox.setItemText(3, _translate("MainWindow", "Сочетание с повторениями"))
        self.Function_ComboBox.setItemText(4, _translate("MainWindow", "Размещение с повторениями"))
        self.Function_ComboBox.setItemText(5, _translate("MainWindow", "Перестановка с повторениями"))
        self.Function_ComboBox.setItemText(6, _translate("MainWindow", "Задача №2"))
        self.Function_ComboBox.setItemText(7, _translate("MainWindow", "Задача №4"))
        self.Function_ComboBox.setItemText(8, _translate("MainWindow", "Задача №5"))

        self.Input_Label1.setText(_translate("MainWindow", "Input_Label1"))
        self.Input_Label2.setText(_translate("MainWindow", "Input_Label2"))
        self.Input_Label3.setText(_translate("MainWindow", "Input_Label2"))
        self.Scroll_Label1.setText(_translate("MainWindow", "Scroll_Label1"))
        self.Scroll_Label2.setText(_translate("MainWindow", "Scroll_Label2"))

        self.Result_Label.setText(_translate("MainWindow", "Результат:"))
        self.Formula_Label.setText(_translate("MainWindow", "Формула:"))
        self.Calculate_Button.setText(_translate("MainWindow", "Рассчитать"))