# Form implementation generated from reading ui file 'Lab_1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from NaturalNumberValidator import NaturalNumberValidator
from PyQt6.QtGui import QValidator, QPixmap
import probabilityFunctions


class Ui_MainWindow(object):
    mListLabels = []
    mListText = []
    maxLengthOfList = 30
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Lab_1 Тютюнов, Лукьяненко, Букин")
        MainWindow.resize(364, 345)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setSpacing(7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Input1_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Input1_Label.setObjectName("Input1_Label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Input1_Label)
        self.Input1_LineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input1_LineEdit.sizePolicy().hasHeightForWidth())
        self.Input1_LineEdit.setSizePolicy(sizePolicy)
        self.Input1_LineEdit.setObjectName("Input1_LineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Input1_LineEdit)
        self.Input2_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Input2_Label.setObjectName("Input2_Label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Input2_Label)
        self.Input2_LineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input2_LineEdit.setObjectName("Input2_LineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Input2_LineEdit)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.permutationsNumbers_Layout = QtWidgets.QVBoxLayout()
        self.permutationsNumbers_Layout.setObjectName("verticalLayout_2")
        self.permutationsNumbers_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.permutationsNumbers_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.permutationsNumbers_label.setObjectName("label_3")
        self.permutationsNumbers_Layout.addWidget(self.permutationsNumbers_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 338, 204))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.formLayoutForScroll = QtWidgets.QFormLayout()
        self.formLayoutForScroll.setContentsMargins(10, 10, 10, 10)
        self.formLayoutForScroll.setSpacing(7)
        self.formLayoutForScroll.setObjectName("formLayoutForScroll")

        self.scrollAreaWidgetContents.setLayout(self.formLayoutForScroll)

        self.permutationsNumbers_Layout.addWidget(self.scrollArea)
        self.verticalLayout_3.addLayout(self.permutationsNumbers_Layout)
        self.label_Result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Result.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_Result)

        self.label_formula = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_formula.setObjectName("label_formula")
        self.verticalLayout_3.addWidget(self.label_formula)

        self.label_photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_photo.setObjectName("label_photo")
        self.verticalLayout_3.addWidget(self.label_photo)

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.setValidators()
        self.setListeners()
        self.changeMod(self.comboBox.currentIndex(), self.comboBox.currentText())

    def setListeners(self):
        self.comboBox.currentIndexChanged.connect(lambda: self.changeMod(self.comboBox.currentIndex(), self.comboBox.currentText()))
        self.Input2_LineEdit.textChanged.connect(lambda: self.mListSizeListener(self.Input2_LineEdit.text()))
        self.pushButton.clicked.connect(lambda: self.calculateResult(self.comboBox.currentIndex()))

    def setValidators(self):
        self.setValidator(self.Input1_LineEdit)
        self.setValidator(self.Input2_LineEdit)

    def setValidator(self, lineEdit):
        naturalValidator = NaturalNumberValidator()
        lineEdit.setValidator(naturalValidator)

    def changeMod(self, index, text):
        match index:
            case 0:
                self.Input2_Label.setVisible(False)
                self.Input2_LineEdit.setVisible(False)
                self.permutationsNumbersVisibility(False)
            case 5:
                self.Input2_Label.setVisible(True)
                self.Input2_Label.setText("количество элементов m")
                self.Input2_LineEdit.setVisible(True)
                self.permutationsNumbersVisibility(True)
                self.setNumOfMListElements(self.getIntFromLineEdit(self.Input2_LineEdit))
            case _:
                self.Input2_Label.setVisible(True)
                self.Input2_Label.setText("M")
                self.Input2_LineEdit.setVisible(True)
                self.permutationsNumbersVisibility(False)

        pixmap = QPixmap(text + ".png").scaledToWidth(400)
        self.label_photo.setPixmap(pixmap)


    def calculateResult(self, numOfOperation):
        try:
            num1 = self.getIntFromLineEdit(self.Input1_LineEdit)
            num2 = self.getIntFromLineEdit(self.Input2_LineEdit)
            match numOfOperation:
                case 0:
                    res = probabilityFunctions.factorial(num1)
                case 1:
                    res = probabilityFunctions.combWithoutRep(num1, num2)
                case 2:
                    res = probabilityFunctions.placeWithoutRep(num1, num2)
                case 3:
                    res = probabilityFunctions.combWithRep(num1, num2)
                case 4:
                    res = probabilityFunctions.placeWithRep(num1, num2)
                case 5:
                    numList = self.getIntListFromLineEditList(self.mListText)
                    res = probabilityFunctions.permutationsWithRep(num1,numList)

            text = ""
            if res == -1:
                text = "Некорректный ввод!"
            else:
                text = "Результат: "+str(res)
        except:
            text = "Невозможно посчитать значение"
        self.label_Result.setText(text)

    def getIntListFromLineEditList(self, lineEditList):
        numList = []
        for lineEdit in lineEditList:
            numList.append(self.getIntFromLineEdit(lineEdit))
        return numList

    def mListSizeListener(self, text):
        if (self.comboBox.currentIndex() != 5):
            return

        self.setNumOfMListElements(min(self.maxLengthOfList, self.getIntFromLineEdit(self.Input2_LineEdit)))

    def getIntFromLineEdit(self, lineEdit):
        text = lineEdit.text()
        validator_state = lineEdit.validator().validate(text, 0)[0]
        if (text == ""):
            return 0
        elif (validator_state == QValidator.State.Acceptable):
            return int(text)

    def setNumOfMListElements(self, num):
        mListLength = len(self.mListText)
        for i in range(num - mListLength):
            self.addMListElement()
        for i in range(mListLength-1, num-1, -1):
            self.mListText[i].deleteLater()
            self.mListLabels[i].deleteLater()
            self.formLayoutForScroll.removeRow(i)
            self.mListLabels.pop()
            self.mListText.pop()

    def addMListElement(self):
        index = len(self.mListText)

        label = QtWidgets.QLabel(parent=self.centralwidget)
        label.setText("m"+str(index)+":")
        lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)

        self.setValidator(lineEdit)

        self.mListLabels.append(label)
        self.mListText.append(lineEdit)

        self.formLayoutForScroll.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayoutForScroll.setWidget(index, QtWidgets.QFormLayout.ItemRole.FieldRole, lineEdit)
    def permutationsNumbersVisibility(self, log):
        self.permutationsNumbers_label.setVisible(log)
        self.scrollArea.setVisible(log)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab_1 Коломойцев, Болдырев, Нуриев"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Перестановка без повторений"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Сочетание без повторений"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Размещение без повторений"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Сочетание с повторениями"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Размещение с повторениями"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Перестановка с повторениями"))
        self.Input1_Label.setText(_translate("MainWindow", "N:"))
        self.Input2_Label.setText(_translate("MainWindow", "M:"))
        self.permutationsNumbers_label.setText(_translate("MainWindow", "Числа для перестановки"))
        self.label_Result.setText(_translate("MainWindow", "Резульат:"))
        self.label_formula.setText(_translate("MainWindow", "Формула:"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
